# Generated by Django 4.1.1 on 2022-09-28 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_image_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='list_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
